"""Streamlit chat UI for DrK_Chat (Enlighten AI).

Run from the repo root:
    conda run -n enlighten streamlit run DrK_Chat/app.py

Grounds replies in Dr. K video transcripts via hybrid RAG, streams the answer
from the vLLM Gemma endpoint, and shows clickable timestamped source citations.
"""
from __future__ import annotations

import streamlit as st

import config
from DrK_Chat import rag
from DrK_Chat import guardrails
from DrK_Chat.embeddings import Embedder
from DrK_Chat.retrieval import Retriever

LOGO = config.ROOT / "static" / "imgs" / "HG_logo.jpg"

st.set_page_config(page_title="Enlighten AI · DrK_Chat", page_icon="🧠", layout="centered")


@st.cache_resource(show_spinner="Loading the knowledge base…")
def get_retriever() -> Retriever:
    return Retriever(embedder=Embedder())


def fmt_ts(seconds: float) -> str:
    s = int(seconds or 0)
    return f"{s // 60}:{s % 60:02d}"


# --- Header & disclaimer ----------------------------------------------------
cols = st.columns([1, 6])
with cols[0]:
    if LOGO.exists():
        st.image(str(LOGO), width=64)
with cols[1]:
    st.title("Enlighten AI")
    st.caption("A reflective companion grounded in Dr. K's (HealthyGamerGG) talks.")

st.warning(
    "**Not a substitute for professional care.** Enlighten is a self-help companion, "
    "not a therapist or medical professional, and cannot diagnose or treat. "
    "If you are in crisis, call or text **988** (US Suicide & Crisis Lifeline) or your "
    "local emergency services.",
    icon="⚠️",
)

with st.sidebar:
    st.header("About")
    st.markdown(
        "Answers are retrieved from Dr. K's video transcripts (hybrid dense + BM25 "
        "search) and generated by a local Gemma model. Sources with timestamps are "
        "shown under each reply."
    )
    k = st.slider("Sources retrieved (k)", 2, 12, config.RETRIEVE_K)
    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()

retriever = get_retriever()
if retriever.size == 0:
    st.info("The knowledge base is empty. Run the scraper and `python -m DrK_Chat.ingest` first.")
    st.stop()

# --- Conversation state -----------------------------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []  # list of {role, content, sources?}


def render_sources(sources: list[dict]) -> None:
    if not sources:
        return
    with st.expander(f"Sources ({len(sources)})"):
        for s in sources:
            ts = fmt_ts(s.get("start_time", 0.0))
            playlist = f" · _{s['playlist_tag']}_" if s.get("playlist_tag") else ""
            st.markdown(f"**[{s['n']}]** [{s['video_title']} @ {ts}]({s['timestamp_url']}){playlist}")


# replay history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg["role"] == "assistant":
            render_sources(msg.get("sources", []))

# --- New turn ---------------------------------------------------------------
if prompt := st.chat_input("What's on your mind?"):
    # Input guardrail first, so a blocked turn can be tagged and kept out of model context.
    decision = guardrails.screen_input(prompt, client=rag.get_client())
    blocked = decision["action"] != "allow"
    st.session_state.messages.append({"role": "user", "content": prompt, "blocked": blocked})
    with st.chat_message("user"):
        st.markdown(prompt)

    if blocked:  # short-circuit crisis / harm / method / injection to a vetted response
        with st.chat_message("assistant"):
            st.markdown(decision["response"])
        st.session_state.messages.append(
            {"role": "assistant", "content": decision["response"], "sources": []})
    else:
        # model_history withholds the text of any prior guard-blocked turn (time-bomb defense)
        history = guardrails.model_history(st.session_state.messages[:-1])
        messages, sources, _ = rag.build(prompt, history=history, k=k, retriever=retriever)
        with st.chat_message("assistant"):
            streamed = st.write_stream(rag.stream_completion(messages))
            text, flagged = guardrails.screen_output(streamed)
            if flagged:  # render the appended disclaimer in this same turn
                st.markdown(text[len(streamed):])
            render_sources(sources)
        st.session_state.messages.append(
            {"role": "assistant", "content": text, "sources": sources})
